import type { Metadata } from "next";
import { Geist, Geist_Mono, Gemunu_Libre, Goldman } from "next/font/google";
import "@/src/styles/globals.css";
import { routing } from "@/src/i18n/routing";
import { getLocale, setRequestLocale } from "next-intl/server";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { QueryProvider } from "@/src/provider/QueryProvider";

export function generateStaticParams(){
  return routing.locales.map(locale=> ({locale}))
}
const gemunuLibre = Gemunu_Libre({
  variable: "--font-gemunu-libre",
  subsets: ["latin"],
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const goldman = Goldman({
  variable: "--font-goldman",
  subsets: ["latin"],
  weight: "400"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode
  params: Promise<{locale: string}>
}
export default async function RootLayout({
  children,
  params
}: Props) {
  const {locale} = await params
  // const  locale1 = await getLocale()
  console.log('the rootlayout locale=', locale)
  if(!hasLocale(routing.locales, locale)){
    notFound()
  }
  setRequestLocale(locale)
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${gemunuLibre.variable} ${goldman.variable} antialiased`}
      >
        <NextIntlClientProvider>
          <QueryProvider>
            {children}
          </QueryProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}


/*
// app/[locale]/page.tsx
import {getTranslations} from 'next-intl/server';

export default async function HomePage() {
  const t = await getTranslations('HomePage');
  
  return (
    <div>
      <h1>{t('title')}</h1>
      <p>{t('description')}</p>
    </div>
  );
}

'use client';
import {useTranslations} from 'next-intl';

export function Counter() {
  const t = useTranslations('HomePage');
  return <button>{t('title')}</button>;
}
*/